<?php

use App\Domain\Inventory\StockWriteGuard;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;
use Tests\Support\CatalogFixture;
use Tests\Support\Props;
use Tests\Support\Staff;
use Tests\Support\T;

use function Pest\Laravel\actingAs;

/*
 * Two products may carry one supplier code (developer, 2026-10-05).
 *
 * ── The decision ────────────────────────────────────────────────────────────────────────────
 *
 * *"A manufacturer's code comes from outside and two of our products can legitimately carry one.
 * The index contradicts that, and it already blocked a real merge. Drop it, and instead surface
 * duplicates: a filter or marker so the team can see two products sharing a supplier code and
 * decide whether that's correct."*
 *
 * So this file has two halves, and they belong together: the constraint is GONE from the schema
 * and the form, and it is PRESENT on the screen. Either half alone is a regression — a database
 * that refuses the truth, or a duplicate nobody ever learns about.
 */

/**
 * Two live products sharing one code, in the two casings the real pair uses. Returns their ids.
 *
 * @return array{0: int, 1: int}
 */
function sharingProducts(string $code = 'SHARED-CODE-01'): array
{
    $first = CatalogFixture::product();
    $second = CatalogFixture::product();

    StockWriteGuard::allow(function () use ($first, $second, $code): void {
        DB::table('catalog_products')->where('id', $first)->update(['sku' => strtolower($code)]);
        DB::table('catalog_products')->where('id', $second)->update(['sku' => strtoupper($code)]);
    });

    return [$first, $second];
}

it('lets two products carry one supplier code, in the database', function () {
    [$first, $second] = sharingProducts();

    // The assertion is that the two writes above did not throw. Read them back so a silent failure
    // cannot pass as success.
    expect(T::str(DB::table('catalog_products')->where('id', $first)->value('sku')))->not->toBe('');
    expect(T::str(DB::table('catalog_products')->where('id', $second)->value('sku')))->not->toBe('');
});

it('no longer carries a unique index on the product supplier code', function () {
    /*
     * Read from the SCHEMA, not from a migration file: a migration that ran once proves nothing
     * about the tree somebody checks out next month, and this is the constraint the whole decision
     * turns on.
     */
    $unique = [];
    foreach (DB::select('SHOW INDEX FROM catalog_products') as $raw) {
        $row = (array) $raw;
        if (($row['Column_name'] ?? null) === 'sku' && T::int($row['Non_unique'] ?? 1) === 0) {
            $unique[] = T::str($row['Key_name'] ?? '');
        }
    }

    expect($unique)->toBe([], 'the supplier code is unique again — two products may share one');
});

it('keeps the VARIANT sku unique, because that one is ours', function () {
    /*
     * The asymmetry is deliberate and this is the test that stops somebody "tidying" it away.
     *
     * A product's `sku` is the manufacturer's code and arrives from outside. A VARIANT's is
     * generated by us from the product's own code and is the identity the inventory ledger
     * resolves — two variants sharing one is a bug, not a supplier's habit.
     */
    $unique = [];
    foreach (DB::select('SHOW INDEX FROM catalog_product_variants') as $raw) {
        $row = (array) $raw;
        if (($row['Column_name'] ?? null) === 'sku' && T::int($row['Non_unique'] ?? 1) === 0) {
            $unique[] = T::str($row['Key_name'] ?? '');
        }
    }

    expect($unique)->not->toBe([], 'the variant sku lost its unique index — that one is ours and must not repeat');
});

it('indexes the supplier code, so the duplicate marker stays a probe', function () {
    // Dropping a unique index also drops the index. The duplicate question is asked once per page
    // and once per filtered query; unindexed it is a scan of every product in the catalogue.
    $indexed = false;
    foreach (DB::select('SHOW INDEX FROM catalog_products') as $raw) {
        $row = (array) $raw;
        if (($row['Column_name'] ?? null) === 'sku') {
            $indexed = true;
        }
    }

    expect($indexed)->toBeTrue('the supplier code has no index at all — every duplicate check is a table scan');
});

it('does not refuse a duplicate supplier code on the product form', function () {
    [$first] = sharingProducts('FORM-DUP-01');

    $code = T::str(DB::table('catalog_products')->where('id', $first)->value('sku'));

    $target = CatalogFixture::product();

    /*
     * The real form route, with a full payload, because the rule under test is the FORM's — the
     * index is only half of the contradiction and the other half was `Rule::unique` in
     * `ProductController::rules()`. A payload of one field would be refused by the other rules and
     * would prove nothing about this one.
     *
     * Written out here rather than borrowed from `ProductFormTest`: a Pest helper defined in
     * another test file is not reliably in scope, and a shared payload that drifts would fail this
     * test for reasons that have nothing to do with supplier codes.
     */
    $watches = CatalogFixture::watchesRoot();
    $response = actingAs(Staff::admin())->put("/manage/storefronts/1/products/{$target}", [
        '_complete' => 1,
        'wa_code' => 'dup-code-'.bin2hex(random_bytes(4)),
        'sku' => $code,
        'brand_id' => T::int(DB::table('catalog_brands')->orderBy('id')->value('id')),
        'selling_price' => '1200.00',
        'purchase_price' => '800.00',
        'sale_price' => null,
        'currency' => 'EGP',
        'low_stock_threshold' => 5,
        'is_active' => true,
        'title' => ['ar' => 'ساعة اختبار', 'en' => 'Test watch'],
        'short_description' => ['ar' => 'وصف', 'en' => 'Description'],
        'long_description' => ['ar' => 'وصف تفصيلي', 'en' => 'Long description'],
        'specs' => [],
        'images' => [],
        'feature_ids' => [],
        'gender_ids' => [],
        'colors' => [],
        'category_ids' => [$watches],
        'primary_category_id' => $watches,
        'is_visible' => false,
        'is_featured' => false,
        'sort_order' => 0,
        'slug' => null,
    ]);

    // Not only "no error on the field" — a refusal elsewhere would satisfy that and prove nothing.
    // The value has to have LANDED, which is what `Rule::unique` used to prevent.
    $response->assertSessionDoesntHaveErrors('sku');

    expect(T::str(DB::table('catalog_products')->where('id', $target)->value('sku')))->toBe($code);
});

it('selects exactly the products sharing a code, and nothing else', function () {
    [$first, $second] = sharingProducts('FLAG-DUP-01');

    // A third product with a code of its own — the control. Without it this test would pass on a
    // filter that simply returned every product with any code at all.
    $alone = CatalogFixture::product();
    StockWriteGuard::allow(function () use ($alone): void {
        DB::table('catalog_products')->where('id', $alone)->update(['sku' => 'FLAG-ALONE-01']);
    });

    $props = Props::of(
        actingAs(Staff::admin())
            ->get('/manage/storefronts/1/products?filters[flag]=shared_sku&per_page=100')
            ->assertOk()
    );

    $ids = [];
    foreach (T::arr(T::arr($props['table'] ?? null)['data'] ?? null) as $row) {
        $ids[] = T::int(T::arr($row)['id'] ?? null);
    }

    expect($ids)->toContain($first);
    expect($ids)->toContain($second);
    expect($ids)->not->toContain($alone);
});

it('counts a shared code case-insensitively, the way the column compares it', function () {
    /*
     * The real pair in this catalogue is `Ap0012` and `AP0012` — one letter's case apart, which
     * MariaDB's collation reads as one value and PHP's array lookup does not. The marker is keyed
     * lowercase on both sides for exactly this row, so this is the test for that keying.
     */
    [$first] = sharingProducts('CASE-DUP-01');

    $props = Props::of(
        actingAs(Staff::admin())
            ->get('/manage/storefronts/1/products?filters[flag]=shared_sku&per_page=100')
            ->assertOk()
    );

    $shared = null;
    foreach (T::arr(T::arr($props['table'] ?? null)['data'] ?? null) as $row) {
        $cast = T::arr($row);
        if (T::int($cast['id'] ?? null) === $first) {
            $shared = T::int($cast['sku_shared'] ?? null);
        }
    }

    expect($shared)->toBe(2, 'the two casings were counted as two different codes');
});

it('reports no sharing for a product whose code is its own', function () {
    $alone = CatalogFixture::product();
    StockWriteGuard::allow(function () use ($alone): void {
        DB::table('catalog_products')->where('id', $alone)->update(['sku' => 'UNIQUE-CODE-'.bin2hex(random_bytes(4))]);
    });

    $props = Props::of(
        actingAs(Staff::admin())
            ->get('/manage/storefronts/1/products?search=UNIQUE-CODE&per_page=100')
            ->assertOk()
    );

    foreach (T::arr(T::arr($props['table'] ?? null)['data'] ?? null) as $row) {
        $cast = T::arr($row);
        if (T::int($cast['id'] ?? null) === $alone) {
            expect(T::int($cast['sku_shared'] ?? null))->toBeLessThan(2);
        }
    }

    // Schema is imported only to keep this file's use-list honest about what it touches.
    expect(Schema::hasTable('catalog_products'))->toBeTrue();
});
